#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

umask "${UMASK}"

if [[ "${VPN_ENABLED}" == "true" ]] && [[ "${VPN_AUTO_PORT_FORWARD}" != "false" ]]; then
    log_inf "[QBITTORRENT] Delaying start until forwarded port is available."
    until [[ -f "${CONFIG_DIR}/wireguard/forwarded_port_validated" ]]; do   
        sleep 1
    done
    forwarded_port=$(sed -n '1p' "${CONFIG_DIR}/wireguard/forwarded_port_validated")
    ARGS="--torrenting-port=${forwarded_port}"
    log_inf "[QBITTORRENT] Starting with forwarded port [${forwarded_port}]."
fi

# shellcheck disable=SC2086
exec s6-setuidgid hotio "${APP_DIR}/qbittorrent-nox-lib${LIBTORRENT//v/}" --profile="${APP_DIR}" --webui-port="${WEBUI_PORTS%%/*}" --confirm-legal-notice ${ARGS}
